---
dist: xenial

# Python versions
language: python
python:
  - "3.8"
  - "3.7"
  - "3.6"

# Ansible versions
env:
  - ANSIBLE_VERSION=latest
  - ANSIBLE_VERSION=2.9.0
  - ANSIBLE_VERSION=2.8.0
  - ANSIBLE_VERSION=2.7.0
  - ANSIBLE_VERSION=2.6.0

# Install pip3
addons:
  apt:
    packages:
    - python3-pip

install:
  # Install ansible
  - |
    if [ "$ANSIBLE_VERSION" = "latest" ]; then
      pip3 install -q ansible
    else
      pip3 install -q ansible~=$ANSIBLE_VERSION
    fi

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/?branch=master
