---
- name: Ensure Flatpak Repositories are Present
  flatpak_remote:
    name: "{{ item.name }}"
    state: present
    flatpakrepo_url: "{{ item.url }}"
    method: system
  loop: "{{ flatpak_repos }}"

- name: Ensure Flatpak Applications are Present 
  flatpak:
    name: "{{ item.name }}"
    state: present
    method: system
    remote: "{{ item.remote | default('flathub') }}"
  loop: "{{ flatpak_apps }}"
...
