---
- name: add repository remote
  flatpak_remote:
    name: "{{ item.name }}"
    state: present
    flatpakrepo_url: "{{ item.url }}"
    method: system
  loop: "{{ flatpak_repos }}"
- name: install application
  flatpak:
    name: "{{ item.name }}"
    state: present
    method: system
    remote: "{{ item.remote | default('flathub') }}"
  loop: "{{ flatpak_apps }}"
...
